"""Executable live vectors checked against a summation oracle and headless play.

Regenerate only for intentional contract changes with --write-vectors, then run
the pinned Wurst interpreter. The literals cover every threshold through 300.
"""
import copy
from pathlib import Path
import sys
import unittest

ROOT = Path(__file__).resolve().parents[1]
sys.path[:0] = [str(ROOT / "tooling"), str(ROOT.parent / "_shared/engine")]
from hero_progression import HeroProgressionRuntime
from hero_progression_catalog import load_catalog

VECTORS = ROOT / "wurst/HeroProgressionVectorsTests.wurst"


def oracle_floor(level):
    return sum(100 * step + 25 * (step - 1) ** 2 for step in range(1, level))


def vector_source():
    source = '''package HeroProgressionVectorsTests
import HeroProgression
import WarcraftRpgRuntime

// Generated by test_live_hero_progression.py --write-vectors. Literal floors
// and costs are independently checked against the headless progression engine.
function checkHeroThreshold(int level, int floor, int cost, int previousCost)
\theroExperienceForLevel(level).assertEquals(floor)
\theroNextLevelExperience(level).assertEquals(cost)
\theroLevelForExperience(floor).assertEquals(level)
\tlet hero = new RpgHero("vector", "Vector", 'Hpal')
\tif level > 1
\t\thero.awardExperience(floor - 1).assertTrue()
\t\thero.level.assertEquals(level - 1)
\t\thero.experience.assertEquals(previousCost - 1)
\t\thero.awardExperience(1).assertTrue()
\thero.level.assertEquals(level)
\thero.experience.assertEquals(0)
\thero.cumulativeExperience().assertEquals(floor)
\thero.skillPoints.assertEquals(level - 1)
\thero.masteryPoints.assertEquals(level div 5)
\thero.choicePoints.assertEquals(level div 10)
\tif level < 300
\t\thero.awardExperience(cost - 1).assertTrue()
\t\thero.level.assertEquals(level)
\t\thero.experience.assertEquals(cost - 1)
\t\thero.awardExperience(1).assertTrue()
\t\thero.level.assertEquals(level + 1)
\t\thero.experience.assertEquals(0)
\t\thero.skillPoints.assertEquals(level)
\t\thero.masteryPoints.assertEquals((level + 1) div 5)
\t\thero.choicePoints.assertEquals((level + 1) div 10)
\telse
\t\thero.awardExperience(300).assertTrue()
\t\thero.level.assertEquals(300)
\t\thero.experience.assertEquals(300)
\t\thero.skillPoints.assertEquals(299)
\t\thero.masteryPoints.assertEquals(60)
\t\thero.choicePoints.assertEquals(30)
\tdestroy hero
'''
    for level in range(1, 301):
        if (level - 1) % 25 == 0:
            source += f"\n@test function liveHeroThresholdBatch{(level - 1) // 25}()\n"
        floor = oracle_floor(level)
        cost = oracle_floor(level + 1) - floor if level < 300 else 0
        previous = floor - oracle_floor(level - 1) if level > 1 else 0
        source += f"\tcheckHeroThreshold({level}, {floor}, {cost}, {previous})\n"
    return source


def runtime(start=1):
    catalog, _ = load_catalog()
    catalog = copy.deepcopy(catalog)
    profile = catalog["characterProfiles"][0]
    profile.update(startingLevel=start, scenarioUnlocks=[])
    catalog["characterProfiles"] = [profile]
    catalog["experienceSources"] = [{"id": "unit", "kind": "quest", "baseAward": 1}]
    return HeroProgressionRuntime(catalog, [profile["id"]]), profile["id"]


class LiveHeroProgressionTests(unittest.TestCase):
    def test_executable_vectors_match_independent_oracle_and_headless_at_every_level(self):
        self.assertEqual(vector_source(), VECTORS.read_text())
        r, ident = runtime()
        for level in range(1, 301):
            floor = oracle_floor(level)
            self.assertEqual(floor, r.experience_for_level(level))
            self.assertEqual(level, r.level_for_experience(floor))
            if level > 1:
                award = floor - r.require(ident)["experience"]
                r.award_experience(ident, "unit", multiplier=award - 1)
                self.assertEqual(level - 1, r.require(ident)["level"])
                r.award_experience(ident, "unit")
            state = r.require(ident)
            self.assertEqual((level, floor, level - 1, level // 5, level // 10),
                             tuple(state[k] for k in ("level", "experience", "skillPoints", "masteryPoints", "choicePoints")))

    def test_reported_regression_cap_and_signed_integer_boundary(self):
        r, ident = runtime()
        r.award_experience(ident, "unit", multiplier=300)
        self.assertEqual((2, 200), (r.require(ident)["level"], r.require(ident)["experience"] - oracle_floor(2)))
        r.award_experience(ident, "unit", multiplier=2147483647 - 300)
        state = r.require(ident)
        self.assertEqual((300, 299, 60, 30), tuple(state[k] for k in ("level", "skillPoints", "masteryPoints", "choicePoints")))
        self.assertEqual(1921357422, state["experience"] - oracle_floor(300))

    def test_accomplished_start_has_no_retrospective_growth(self):
        for start in (5, 9, 10, 64, 66, 115, 299, 300):
            r, ident = runtime(start)
            self.assertEqual((0, 0, 0), tuple(r.require(ident)[k] for k in ("skillPoints", "masteryPoints", "choicePoints")))
            r.award_experience(ident, "unit", multiplier=2147483647 - oracle_floor(start))
            self.assertEqual((300 - start, 60 - start // 5, 30 - start // 10),
                             tuple(r.require(ident)[k] for k in ("skillPoints", "masteryPoints", "choicePoints")))


if __name__ == "__main__":
    if sys.argv[1:] == ["--write-vectors"]:
        VECTORS.write_text(vector_source())
    else:
        unittest.main()
