"""Cross-language quote vectors and an independent per-edge rational oracle.

Run this file with --write-vectors after intentional contract changes, then run
the checked-in executable Wurst vectors through the pinned interpreter.
"""
from fractions import Fraction
import itertools
import math
from pathlib import Path
import random
import sys
import unittest

from test_playable_trade import fixtures, trade

PROJECT = Path(__file__).resolve().parents[1]
VECTORS = PROJECT / "wurst/TradePricingVectorsTests.wurst"


def catalogs(stock=100, target=100, base=10, units=1, elasticity=1000,
             spread=80, floor=350, ceiling=4000):
    tc, ec, es = fixtures()
    tc["goods"][0].update(basePriceMinor=base, quantityUnitsPerDisplayUnit=units,
                          priceElasticityPermille=elasticity)
    tc["marketRules"][0].update(targetStockUnits={"spice": target}, spreadPermille=spread,
                                priceFloorPermille=floor, priceCeilingPermille=ceiling)
    es["storeBalances"][0]["goods"][0]["quantityUnits"] = stock
    return tc, ec, es


def oracle(stock, target, base, quantity, side, units=1, elasticity=1000,
           spread=80, floor=350, ceiling=4000, conditions=None):
    """Enumerate edges using rational arithmetic, with no production batching."""
    c = conditions or {}
    adjustment = sum(c.get(k, 0) for k in ("shortagePermille", "eventPermille", "blockadePermille", "warPermille", "occupationPermille"))
    adjustment += math.floor(Fraction(c.get("consumptionPermille", 1000) - c.get("productionPermille", 1000), 2))
    adjustment -= math.floor(Fraction(c.get("tradeConnectivityPermille", 1000) - 1000, 3))
    adjustment -= c.get("technologyPermille", 0) + c.get("institutionPermille", 0)
    endpoints = range(stock - quantity + 1, stock + 1) if side == "buy" else range(stock + 1, stock + quantity + 1)
    total = Fraction(0)
    for upper in endpoints:
        scarcity = min(2000, max(-750, math.floor(Fraction((target - upper) * elasticity, target))))
        pressure = min(ceiling, max(floor, 1000 + scarcity + adjustment))
        raw = max(1, math.floor(Fraction(base * pressure, 1000) + Fraction(1, 2)))
        price = max(1, math.floor(Fraction(raw * (1000 + spread if side == "buy" else 1000 - spread), 1000)))
        total += Fraction(price, units)
    return math.ceil(total) if side == "buy" else math.floor(total)


def vector_rows():
    # Every row executes the real RuntimeMarket quote, including current live
    # modifiers. Fractional display units and zero-settlement sells are covered.
    rows = []
    for stock, target, base, units, elasticity in (
        (100, 100, 10, 1, 1000), (400, 100, 37, 1, 1450),
        (7, 101, 99, 100, 1000), (101, 37, 501, 7, 333),
        (13, 13, 1, 3, 0), (240, 320, 540, 100, 1450),
    ):
        for quantity, spread in itertools.product(sorted({1, min(2, stock), min(75, stock), stock}), (0, 80, 125)):
            rows.append((stock, target, base, quantity, units, elasticity, spread, 350, 4000, 0, 0, 0, 1000, 1000, 0, 0))
    for shortage, event, technology, production, consumption, blockade, occupation in (
        (350, 117, 0, 1001, 1000, 0, 0), (0, -733, 170, 1250, 1000, 0, 0),
        (2000, 1200, 0, 775, 1425, 1, 1), (0, -2000, 450, 1000, 1001, 0, 0),
    ):
        rows.append((101, 77, 157, 75, 7, 1450, 80, 500, 1750, shortage, event, technology, production, consumption, blockade, occupation))
    rows.append((100, 100, 10, 75, 1, 1000, 1000, 350, 4000, 0, 0, 0, 1000, 1000, 0, 0))
    return rows


def vector_conditions(row):
    return dict(zip(("shortagePermille", "eventPermille", "technologyPermille", "productionPermille", "consumptionPermille", "blockadePermille", "occupationPermille"),
                    (*row[9:14], row[14] * 500, row[15] * 400)))


def vector_amount(row, side):
    stock, target, base, quantity, units, elasticity, spread, floor, ceiling = row[:9]
    tc, ec, es = catalogs(stock, target, base, units, elasticity, spread, floor, ceiling)
    try:
        return trade.quote(tc, ec, es, "calicut", "spice", side, quantity, vector_conditions(row))["amountMinor"]
    except trade.TradeError as error:
        if "minimum currency settlement" not in str(error):
            raise
        return 0


def vector_source():
    source = '''package TradePricingVectorsTests
import PlayableTrade

// Generated by tests/test_trade_pricing.py --write-vectors. Python checks every
// literal against trade.quote and an independent rational per-edge oracle.
function checkQuote(int stock,int target,int basePrice,int quantity,int units,int elasticity,int spread,int floor,int ceiling,int shortage,int eventModifier,int technology,int production,int consumption,int blockade,int occupation,int buy,int sell)
\tlet market=new RuntimeMarket("vector","cargo",stock,1000000,basePrice,basePrice)
\tmarket.targetStock=target
\tmarket.pricing.quantityUnitsPerDisplayUnit=units
\tmarket.pricing.elasticityPermille=elasticity
\tmarket.pricing.spreadPermille=spread
\tmarket.pricing.priceFloorPermille=floor
\tmarket.pricing.priceCeilingPermille=ceiling
\tmarket.shortagePermille=shortage
\tmarket.eventPermille=eventModifier
\tmarket.technologyPermille=technology
\tmarket.productionPermille=production
\tmarket.consumptionPermille=consumption
\tmarket.blockaded=blockade==1
\tmarket.occupiedByHostile=occupation==1
\tmarket.quoteAmount(quantity,true).assertEquals(buy)
\tmarket.quoteAmount(quantity,false).assertEquals(sell)
\tdestroy market.pricing
\tdestroy market
'''
    for index, row in enumerate(vector_rows()):
        if index % 8 == 0:
            source += f"\n@test function liveQuoteContractBatch{index // 8}()\n"
        source += "\tcheckQuote(" + ",".join(map(str, (*row, vector_amount(row, "buy"), vector_amount(row, "sell")))) + ")\n"
    return source


class TradePricingTests(unittest.TestCase):
    def test_checked_in_executable_live_vectors_match_authority_and_rational_oracle(self):
        self.assertEqual(vector_source(), VECTORS.read_text())
        for row in vector_rows():
            stock, target, base, quantity, units, elasticity, spread, floor, ceiling = row[:9]
            for side in ("buy", "sell"):
                with self.subTest(row=row, side=side):
                    self.assertEqual(oracle(stock, target, base, quantity, side, units, elasticity, spread, floor, ceiling, vector_conditions(row)), vector_amount(row, side))

    def test_reported_exploit_independently_calculated(self):
        # Stock edges 100..26: five base-10 units and ten each of base 11..17.
        buy = 5 * 10 + 10 * (11 + 12 + 14 + 15 + 16 + 17 + 18)
        sell = 5 * 9 + 10 * (10 + 11 + 11 + 12 + 13 + 14 + 15)
        self.assertEqual((1080, 905), (buy, sell))
        tc, ec, es = catalogs()
        self.assertEqual(buy, trade.quote(tc, ec, es, "calicut", "spice", "buy", 75)["amountMinor"])
        es["storeBalances"][0]["goods"][0]["quantityUnits"] = 25
        self.assertEqual(sell, trade.quote(tc, ec, es, "calicut", "spice", "sell", 75)["amountMinor"])

    def test_random_partitions_reverse_sequences_and_repeated_cycles_cannot_mint_money(self):
        rng = random.Random(390)
        for case in range(120):
            stock, target = rng.randint(80, 400), rng.randint(1, 200)
            units, base = rng.choice((1, 3, 100)), rng.randint(400, 800)
            spread = rng.choice((0, 1, 80, 125))
            tc, ec, es = catalogs(stock, target, base, units, rng.randint(0, 1800), spread)
            conditions = {"eventPermille": rng.randint(-600, 1800), "warPermille": 51,
                          "tradeConnectivityPermille": 1201, "institutionPermille": 33}
            for reverse in (False, True):
                position, money = stock, 1000000
                for cycle in range(3):
                    quantity = rng.randint(10, 75)
                    for side in (("sell", "buy") if reverse else ("buy", "sell")):
                        remaining = quantity
                        while remaining:
                            take = rng.randint(1, remaining)
                            es["storeBalances"][0]["goods"][0]["quantityUnits"] = position
                            q = trade.quote(tc, ec, es, "calicut", "spice", side, take, conditions)["amountMinor"]
                            self.assertEqual(oracle(position, target, base, take, side, units, tc["goods"][0]["priceElasticityPermille"], spread, conditions=conditions), q)
                            money += q if side == "sell" else -q
                            position += take if side == "sell" else -take
                            remaining -= take
                    self.assertEqual(stock, position)
                    self.assertLessEqual(money, 1000000, (case, cycle, reverse))

    def test_bulk_and_partitioned_orders_obey_settlement_rounding_inequalities(self):
        for stock, target, base, units in ((100, 100, 10, 1), (250, 100, 100, 3), (200, 5, 540, 100)):
            for side, spread in itertools.product(("buy", "sell"), (0, 80)):
                tc, ec, es = catalogs(stock, target, base, units, spread=spread)
                whole = trade.quote(tc, ec, es, "calicut", "spice", side, 75)["amountMinor"]
                split = 0
                for quantity in (1, 24, 17, 33):
                    split += trade.quote(tc, ec, es, "calicut", "spice", side, quantity)["amountMinor"]
                    es["storeBalances"][0]["goods"][0]["quantityUnits"] += quantity if side == "sell" else -quantity
                if side == "buy":
                    self.assertGreaterEqual(split, whole)
                else:
                    self.assertLessEqual(split, whole)


if __name__ == "__main__":
    if sys.argv[1:] == ["--write-vectors"]:
        VECTORS.write_text(vector_source())
    else:
        unittest.main()
