"""Executable Wurst parity vectors from the independent inventory resolver."""
import copy
import json
from pathlib import Path
import sys
import unittest

PROJECT = Path(__file__).resolve().parents[1]
sys.path[:0] = [str(PROJECT.parent / '_shared/engine'), str(PROJECT.parent / '_shared/tooling')]
from inventory import resolve_equipment_bonuses, validate_catalog
from equipment_sets import equipment_sets_wurst
from player_items import equipment_set_definitions

VECTORS = PROJECT / 'wurst/EquipmentSetVectorsTests.wurst'


def fixture(policy, duplicates):
    items = [(name, slots) for name, slots in (
        ('coat', ['chest']), ('hat', ['head']), ('left_ring', ['left']),
        ('right_ring', ['right']), ('wrong_slot', ['other', 'head']))]
    thresholds = [{'id': 'one', 'pieceCount': 1, 'effectIds': ['guard'], 'tierPolicy': policy},
                  {'id': 'two', 'pieceCount': 2, 'effectIds': ['mobility', 'guard'], 'tierPolicy': policy},
                  {'id': 'three', 'pieceCount': 3, 'effectIds': ['mastery'], 'tierPolicy': policy}]
    if policy == 'replacement':
        thresholds[0]['tierPolicy'] = 'cumulative'
        thresholds[1]['replacesThresholdIds'] = ['one']
        thresholds[2]['replacesThresholdIds'] = ['two']
    for tier in thresholds:
        tier.setdefault('replacesThresholdIds', [])
    return {
        'schemaVersion': 1,
        'itemTypes': [{'id': name, 'category': 'equipment', 'stackable': False,
                       'stackLimit': 1, 'equipmentSlotTypes': slots} for name, slots in items],
        'equipmentSlots': [{'id': slot, 'slotType': slot} for slot in ('chest', 'head', 'left', 'right', 'other')],
        'backpackTypes': [],
        'backpackUnlockTiers': [{'id': 'empty', 'tier': 1, 'activeBackpackSlots': 0, 'maxUnlockedSlotsPerBackpack': 0}],
        # Opaque oracle fixture payloads, not scenario gameplay bindings.
        'derivedEffects': [{'id': ident, 'modifiers': {'testReference': ident}} for ident in ('guard', 'mobility', 'mastery')],
        'equipmentSetPieces': [
            {'id': 'coat_piece', 'itemTypeIds': ['coat']},
            {'id': 'hat_piece', 'itemTypeIds': ['hat', 'wrong_slot'], 'equipmentSlotTypes': ['head']},
            {'id': 'ring_piece', 'itemTypeIds': ['left_ring', 'right_ring']}],
        'equipmentSets': [{'id': 'fixture', 'pieceIds': ['coat_piece', 'hat_piece', 'ring_piece'],
                           'allowDuplicatePieces': duplicates, 'thresholds': list(reversed(thresholds))}],
    }


def vector_source():
    source = '''package EquipmentSetVectorsTests
import EquipmentSetTests
import WarcraftRpgRuntime

// Generated by test_equipment_sets.py --write-vectors. Expected identities come
// from inventory.resolve_equipment_bonuses; commands and projection are live.
'''
    for policy, duplicates in (('cumulative', False), ('exclusive', False),
                               ('replacement', False), ('cumulative', True)):
        data = fixture(policy, duplicates)
        validate_catalog(data)
        source += f'\n@test function equipmentSetParity_{policy}_{str(duplicates).lower()}()\n'
        source += '\tlet f = new SetParityFixture()\n\tf.addHero("alpha")\n\tf.addHero("beta")\n'
        source += '\n'.join(equipment_sets_wurst(data, str)).replace('runtime.', 'f.rpg.') + '\n'
        slots = {row['id']: row['equipmentSlotTypes'][0] for row in data['itemTypes']}
        for row in data['itemTypes']:
            source += f'\tf.rpg.inventory.registerItem(new RpgItem("{row["id"]}","Item","{slots[row["id"]]}","common",1,0))\n'
            source += f'\tf.rpg.inventory.grant("{row["id"]}").assertTrue()\n'
        states = {hero: {'ownerId': hero, 'backpackUnlockTierId': 'empty', 'outerSlots': [None] * 6,
                         'activeBackpacks': [], 'equipment': {slot: None for slot in slots.values()}}
                  for hero in ('alpha', 'beta')}
        actions = [('equip', 'alpha', 'coat'), ('equip', 'beta', 'hat'),
                   ('equip', 'alpha', 'left_ring'), ('equip', 'alpha', 'right_ring'),
                   ('equip', 'alpha', 'wrong_slot'), ('unequip', 'beta', 'head'),
                   ('equip', 'alpha', 'hat'), ('unequip', 'alpha', 'chest'),
                   ('unequip', 'alpha', 'left'), ('unequip', 'alpha', 'right'),
                   ('unequip', 'alpha', 'head'), ('unequip', 'alpha', 'other')]
        for verb, hero, ident in actions:
            state = states[hero]
            if verb == 'equip':
                state['equipment'][slots[ident]] = {'instanceId': ident + '_copy', 'itemTypeId': ident, 'quantity': 1}
            else:
                state['equipment'][ident] = None
            source += f'\tf.action("/{verb} {hero} {ident}")\n'
            for wearer, state in states.items():
                resolved = resolve_equipment_bonuses(data, state)
                count = resolved.set_bonuses[0].equipped_piece_count if resolved.set_bonuses else 0
                identities = ''.join(f'{wearer}|{bonus.set_id}|{bonus.threshold_id}|{effect};'
                                     for bonus in resolved.set_bonuses for effect in bonus.effect_ids)
                source += f'\tf.check("{wearer}", "fixture", {count}, "{identities}")\n'
            if verb == 'equip' and hero == 'alpha' and ident == 'hat':
                status = 'active' if policy == 'cumulative' else 'superseded'
                source += f'\tf.inspect("alpha", "one (1 pieces): {status} | Effects: guard")\n'
            source += '\tf.rpg.reconcile("player")\n'
        source += '\tf.natives.totalWrites.assertEquals(0)\n'
        source += '\tf.rpg.inventory.ownedCount.assertEquals(5)\n'
    return source


class EquipmentSetParityTests(unittest.TestCase):
    def test_live_vectors_match_headless_authority(self):
        self.assertEqual(vector_source(), VECTORS.read_text())

    def test_explicit_piece_tier_and_policy_identities_survive_normalization(self):
        data = json.loads((PROJECT / 'scenario/inventory/player-use-catalog.json').read_text())
        tier = data['equipmentSets'][0]['thresholds'][1]
        tier.update(id='middle', tierPolicy='replacement', replacesThresholdIds=['pieces_2'])
        tier['effectIds'].append('set_resilience')
        definition = equipment_set_definitions(data)['equipmentSets'][0]
        self.assertEqual(definition['thresholds'][1], {**tier})
        data['equipmentSets'][0]['allowDuplicatePieces'] = True
        self.assertTrue(equipment_set_definitions(data)['equipmentSets'][0]['allowDuplicatePieces'])

    def test_normalization_does_not_invent_effect_payloads(self):
        data = json.loads((PROJECT / 'scenario/inventory/player-use-catalog.json').read_text())
        before = copy.deepcopy(data)
        result = equipment_set_definitions(data)
        self.assertEqual(data, before)
        self.assertEqual([{'id': ident} for ident in sorted(row['id'] for row in data['effects'])], result['derivedEffects'])


if __name__ == '__main__':
    if '--write-vectors' in sys.argv:
        VECTORS.write_text(vector_source())
    else:
        unittest.main()
