"""Headless allocation oracle and generated production-command parity vectors."""
import copy
import json
from pathlib import Path
import sys
import tempfile
import unittest

ROOT = Path(__file__).resolve().parents[1]
sys.path[:0] = [str(ROOT / "tooling"), str(ROOT.parent / "_shared/tooling"),
               str(ROOT.parent / "_shared/engine")]
from hero_progression import HeroProgressionRuntime, HeroProgressionError
from hero_progression_catalog import load_catalog
from hero_starting_profiles import starting_definitions, rank_text
from hero_allocations import allocation_definitions, allocation_wurst
from package_wurst_map import generate, load_config, verify_generated

VECTORS = ROOT / "wurst/HeroAllocationVectorsTests.wurst"


def vector_source():
    source = """package HeroAllocationVectorsTests
import HeroAllocationTests
import WarcraftRpgRuntime

// Generated by test_hero_allocations.py --write-vectors using the independent
// Python authority. Each action dispatches production commands after a valid
// registered quest reward; rejected actions compare complete live RPG state.
"""
    for label, start, target, rank, tree in (
        ("chain", 1, 30, 0, "martial_signature"),
        ("level", 1, 9, 0, "martial_signature"),
        ("zero", 1, 1, 0, "martial_signature"),
        ("cap", 99, 100, 99, "martial_signature"),
        ("civic", 1, 30, 0, "civic_signature"),
        ("discovery", 1, 30, 0, "discovery_signature"),
    ):
        catalog, _ = load_catalog()
        profile = {"id": "hero", "startingLevel": start, "startingLocationId": "lisbon",
                   "startingSkills": [{"skillId": "navigation", "rank": rank}],
                   "startingMasteries": [{"masteryId": "sea_command", "rank": rank}],
                   "personalTreeId": tree, "scenarioUnlocks": []}
        catalog["characterProfiles"] = [profile]
        catalog["experienceSources"] = [{"id": "quest", "kind": "quest", "baseAward": 1}]
        oracle = HeroProgressionRuntime(catalog, ["hero"])
        reward = max(1, oracle.experience_for_level(target) - oracle.experience_for_level(start))
        oracle.award_experience("hero", "quest", multiplier=reward)
        source += f'\n@test function allocationParity_{label}()\n'
        source += f'\tlet f = new AllocationFixture({start}, "navigation:{rank}~", "sea_command:{rank}~", "{tree}")\n'
        source += f'\tf.earn({reward})\n'
        prefix = tree.split("_")[0]
        sequence = [("perk", "civic_veteran" if prefix == "martial" else "martial_initiate"),
                    ("perk", f"{prefix}_veteran"), ("perk", f"{prefix}_initiate"),
                    ("perk", f"{prefix}_initiate"), ("perk", f"{prefix}_veteran"),
                    ("perk", f"{prefix}_veteran"), ("skill", "navigation"),
                    ("skill", "navigation"), ("mastery", "sea_command"),
                    ("mastery", "sea_command"), ("skill", "unknown"),
                    ("mastery", "unknown"), ("perk", "unknown")]
        methods = {"skill": ("improveskill", oracle.improve_skill),
                   "mastery": ("improvemastery", oracle.improve_mastery),
                   "perk": ("chooseperk", oracle.choose_perk)}
        for kind, ident in sequence:
            before = oracle.snapshot()
            command, method = methods[kind]
            try:
                method("hero", ident)
                accepted = True
            except HeroProgressionError:
                accepted = False
                assert before == oracle.snapshot()
            state = oracle.require("hero")
            source += f'\tf.action("/{command} hero {ident}", {str(accepted).lower()})\n'
            values = [state[k] for k in ("skillPoints", "masteryPoints", "choicePoints")]
            values += [state["skills"]["navigation"], state["masteries"]["sea_command"],
                       "martial_initiate" in state["perkIds"], "martial_veteran" in state["perkIds"]]
            source += '\tf.check(' + ', '.join(str(v).lower() for v in values) + ')\n'
            if prefix != "martial":
                for perk in catalog["perks"]:
                    if perk["id"].startswith(prefix):
                        selected = str(perk["id"] in state["perkIds"]).lower()
                        source += f'\tf.hero.hasPerk("{perk["id"]}").assertEquals({selected})\n'
                        source += f'\tf.rpg.hasSelectedAbility("hero", "{perk["abilityId"]}").assertEquals({selected})\n'
    return source


class HeroAllocationTests(unittest.TestCase):
    def test_executable_allocation_vectors_match_headless_authority(self):
        self.assertEqual(vector_source(), VECTORS.read_text())

    def test_generated_definitions_keep_every_authored_reference_and_registration(self):
        catalog, _ = load_catalog()
        world = json.loads((ROOT / "scenario/world/world.json").read_text())
        definitions = allocation_definitions(catalog, starting_definitions(world, catalog))
        with tempfile.TemporaryDirectory() as directory:
            target = Path(directory)
            config = load_config(ROOT / "package.json")
            generate(config, target)
            verify_generated(config, target)
            runtime = json.loads((target / "scenario-runtime.json").read_text())
            source = (target / "ScenarioData.wurst").read_text()
            self.assertEqual(definitions, runtime["heroAllocationDefinitions"])
            for key in ("skills", "masteries", "abilities", "perks", "personalTrees"):
                self.assertEqual(sorted(catalog[key], key=lambda r: r["id"]), definitions[key])
            for line in allocation_wurst(definitions, lambda s: s):
                self.assertIn(line, source)
            self.assertFalse(definitions["respecSupported"])

    def test_invalid_allocation_catalogue_is_rejected(self):
        catalog, _ = load_catalog()
        starts = starting_definitions({"characters": []}, catalog)
        changes = [lambda c: c["perks"][0].update(abilityId="missing"),
                   lambda c: c["perks"][0].update(prerequisitePerkIds=["missing"]),
                   lambda c: c["perks"][0].update(prerequisitePerkIds=["martial_initiate"]),
                   lambda c: c["perks"][0].update(prerequisitePerkIds=["martial_veteran"]),
                   lambda c: c["perks"][0].update(prerequisitePerkIds=["civic_initiate"]),
                   lambda c: c["perks"][1].update(prerequisitePerkIds=["martial_initiate"] * 2),
                   lambda c: c["personalTrees"][0].update(perkIds=["missing"]),
                   lambda c: c["personalTrees"][0].update(perkIds=[]),
                   lambda c: c["personalTrees"][0].update(perkIds=["martial_initiate"] * 2),
                   lambda c: c["respec"].update(supported=True)]
        changes += [lambda c, value=v: c["perks"][0].update(minimumLevel=value)
                    for v in (0, 301, True, "10", 1.5)]
        changes += [lambda c, value=v: c["skills"][0].update(id=value)
                    for v in ("", "A", "bad~id", "bad,id")]
        for change in changes:
            changed = copy.deepcopy(catalog)
            change(changed)
            with self.subTest(catalog=changed), self.assertRaises(ValueError):
                allocation_definitions(changed, starts)
        for key in ("skills", "masteries", "abilities", "perks", "personalTrees"):
            changed = copy.deepcopy(catalog)
            changed[key].append(changed[key][0])
            with self.subTest(duplicate=key), self.assertRaises(ValueError):
                allocation_definitions(changed, starts)

    def test_catalogue_less_scenarios_retain_explicit_rank_definitions(self):
        starts = starting_definitions({"characters": [{"id": "other", "skills": [{"skillId": "craft", "rating": 40}]}]})
        definitions = allocation_definitions(None, starts)
        self.assertEqual([{"id": "craft", "name": "craft"}], definitions["skills"])
        self.assertEqual([], definitions["perks"])


if __name__ == "__main__":
    if sys.argv[1:] == ["--write-vectors"]:
        VECTORS.write_text(vector_source())
    else:
        unittest.main()
